# Generated by Django 5.2.1 on 2025-05-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_postlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
