# Generated by Django 5.2.1 on 2025-05-31 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_posts_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='MyAPI.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAPI.users')),
            ],
            options={
                'verbose_name': 'Post Save',
                'verbose_name_plural': 'Post Saves',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
