# Generated by Django 5.2.1 on 2025-05-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_postsave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postsave',
            name='created_at',
        ),
    ]
